"""empty message

Revision ID: 9cad6e7f4380
Revises: 8d6e438cea71
Create Date: 2025-05-07 15:19:55.343610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cad6e7f4380'
down_revision = '8d6e438cea71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('starships_favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starships_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('starships_favorites_Starships_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'starships', ['starships_id'], ['id'])
        batch_op.drop_column('Starships_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('starships_favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Starships_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('starships_favorites_Starships_id_fkey', 'starships', ['Starships_id'], ['id'])
        batch_op.drop_column('starships_id')

    # ### end Alembic commands ###
